<?php

namespace AppBundle\Repository;

/**
 * MassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MassageRepository extends \Doctrine\ORM\EntityRepository
{
}
